<?php
/**
 * @file e3_js.module
 * Loads underscore, creates e3_js config, loads correct version of e3_js
 */


/**
 * Implements hook_init().
 */
function e3_js_init() {

  if($env = variable_get('e3_js_prod', '0')) {
    switch($env) {
      case 0:
        $script = 'e3_js.js';
        break;
      case 1:
        $script = 'e3_js.min.js';
        break;
    }
  } else {
    watchdog('e3_js has not been configured.', WATCHDOG_ERROR);
    // Assume we don't need debug mode
    $script = 'e3_js.min.js';
  }

  if (arg(0) != 'admin') {

    $js_path = drupal_get_path('module', 'e3_js') . '/' . $script;

    drupal_add_js(libraries_get_path('underscore') . '/underscore.js',
      array(
        'weight' => -100,
        'scope' => 'header',
        'preprocess' => true
      ), 'setting'
    );

    drupal_add_js($js_path,
      array(
        'weight' => -50,
        'scope' => 'header',
        'preprocess' => true
      ), 'setting'
    );

  }
}

/**
 *  Implements hook_menu().
 */
function e3_js_menu(){
  $items = array();

  $items['admin/config/development/e3js'] = array(
    'title' => 'E3 JS Settings',
    'description' => 'Configuration for the e3_js library.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('e3_js_admin_form'),
    'access arguments' => array('access devel information'),
  );

  return $items;
}

/**
 * Creates the admin settings form.
 * @return mixed
 */
function e3_js_admin_form() {
  $form['e3_js_prod'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use minified js'),
    '#default_value' => variable_get('e3_js_prod', 0),
  );

  return system_settings_form($form);
}